# All commands below are run from root directory of repository by CodeBuild
version: 0.2

env:
  parameter-store:
    # Serverless Framework v4 requires authentication for every deploy.
    SERVERLESS_LICENSE_KEY: "/discogs-market-monitor/serverless_license_key"
  variables:
    TF_VAR_region: "ap-southeast-2"
    TF_VAR_name: "discogs-market-monitor"
    TF_VAR_ssm_parameter_arns: '["arn:aws:ssm:ap-southeast-2:352311918919:parameter/shared/*", "arn:aws:ssm:ap-southeast-2:352311918919:parameter/discogs-market-monitor/*"]'
    TF_VAR_build_docker_image: "jch254/docker-node-terraform-aws"
    TF_VAR_build_docker_tag: "22.x"
    TF_VAR_buildspec: "buildspec.yml"
    TF_VAR_source_location: "https://github.com/jch254/discogs-market-monitor.git"
    TF_VAR_cache_bucket: "jch254-codebuild-cache/discogs-market-monitor"
    TF_VAR_build_compute_type: "BUILD_GENERAL1_MEDIUM"
    REMOTE_STATE_BUCKET: "jch254-terraform-remote-state"
    REMOTE_STATE_REGION: "ap-southeast-4"

phases:
  install:
    commands:
      # Workaround until CodeBuild/CodePipeline retains file permissions
      - find ./infrastructure -name "*.bash" -exec chmod +x {} \;
      - ./infrastructure/install.bash

  build:
    commands:
      - ./infrastructure/deploy-infrastructure.bash
      - ./infrastructure/deploy-serverless.bash

cache:
   paths:
     - 'infrastructure/.terraform/modules/**/*'
     - 'infrastructure/.terraform/plugins/**/*'
     - 'node_modules/.pnpm/**/*'