org: jch254
app: discogs-market-monitor
service: discogs-market-monitor

frameworkVersion: "4"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs22.x
  stage: prod
  region: ap-southeast-2

functions:
  handler:
    handler: src/index.handler
    memorySize: 256
    timeout: 900
    environment:
      DISCOGS_USER_TOKEN: ${ssm:/discogs-market-monitor/discogs_user_token, env:DISCOGS_USER_TOKEN, ''}
      RESEND_API_KEY: ${ssm:/discogs-market-monitor/resend_api_key, env:RESEND_API_KEY, ''}
      SENDER_EMAIL: ${ssm:/discogs-market-monitor/sender_email, env:SENDER_EMAIL, ''}
