service: discogs-market-monitor

frameworkVersion: '2 || 3'

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.ts
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk
  secrets: ${ssm:/aws/reference/secretsmanager/prod/discogs-market-monitor/secrets}

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-southeast-2
  environment:
    DISCOGS_USER_TOKEN: ${self:custom.secrets.DISCOGS_USER_TOKEN}
    SENDGRID_API_KEY: ${self:custom.secrets.SENDGRID_API_KEY}
    DISCOGS_USERNAME: ${self:custom.secrets.DISCOGS_USERNAME}
    SHIPS_FROM: ${self:custom.secrets.SHIPS_FROM}
    DESTINATION_EMAIL: ${self:custom.secrets.DESTINATION_EMAIL}
    SENDER_EMAIL: ${self:custom.secrets.SENDER_EMAIL}

functions:
  handler:
    handler: src/index.handler
    memorySize: 3008
    timeout: 900
    events:
      # Invoke Lambda function every 12 hours
      - schedule: rate(12 hours)
