service: discogs-market-monitor

frameworkVersion: "2 || 3"

useDotenv: true

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    webpackConfig: ./webpack.config.ts
    packager: "pnpm"
    includeModules:
      forceExclude:
        - aws-sdk

provider:
  name: aws
  runtime: nodejs22.x
  stage: prod
  region: ap-southeast-2

functions:
  handler:
    handler: src/index.handler
    memorySize: 256
    timeout: 900
    environment:
      DISCOGS_USER_TOKEN: ${ssm:/discogs-market-monitor/discogs_user_token}
      SENDGRID_API_KEY: ${ssm:/discogs-market-monitor/sendgrid_api_key}
      SENDER_EMAIL: ${ssm:/discogs-market-monitor/sender_email}
